cice5: explicitly set the rpath of library dependencies
ACCESS-NRI/spack_packages pull request #31
Opened 2023-08-02 14:39 UTC by harshula

* Print the generated config file to stdout.
* Close #14.

2023-08-03 06:23 UTC, aidanheerdegen requested changes
I think just that one change required.

2023-08-03 06:23 UTC, aidanheerdegen commented on packages/cice5/package.py
> +        path = join_path(spec["parallelio"].prefix, "lib")
Should this be
```suggestion
        path = join_path(spec[name].prefix, "lib")
```

2023-08-03 11:05 UTC, harshula commented on packages/cice5/package.py
> +        path = join_path(spec["parallelio"].prefix, "lib")
Yes, that's a bug! Good catch.

2023-08-03 23:42 UTC, aidanheerdegen approved these changes
Looks good to me. If you had the output of the linker flags handy in a buffer somewhere it would be nice to paste it into the PR to show how all that logic pans out in an example build, but don't bother running it just to get that.

2023-08-03 23:44 UTC, merged

2023-08-04 00:05 UTC, harshula commented
Good idea. I have it in my notes, so I've added it to the issue where the rest of the documentation resides.