access-om2: Added link to git repo, removed hardcoded version string
ACCESS-NRI/spack_packages pull request #53
Opened 2023-11-13 01:55 UTC by CodeGat

In this PR, we remove the hardcoded `version("2023.0.001-1")` and add in the git repo, so we can associate a particular build of access-om2 with a git commit (aka, so we can have a `spack install access-om2@git.2023.11.20` for example).

2023-11-14 22:20 UTC, aidanheerdegen commented
This change makes it simpler/easier to update to a new version of the package because it doesn't require a change in this SPD?

I suppose that has significant advantages for our CI/CD testing pipeline as it doesn't require rebuilding and deploying the dependency containers as frequently?

2023-11-14 22:27 UTC, CodeGat commented
Yes. Especially for CD as right now every version of ACCESS-OM2 will be `2023.01.001-1` to spack. The other alternative was to not use the ACCESS-OM2 SBD entirely, instead having the spack.yaml being a set of the dependencies already noted in the SBD.

2023-11-16 00:33 UTC, harshula approved these changes

2023-11-16 01:22 UTC, harshula requested changes
We need to have a single default version(), same as the SPDs that we discussed, otherwise this happens:
```
$ spack install access-om2
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "access-om2"
```
Have a look at the SPDs and pick something you think is appropriate.

2023-11-16 01:33 UTC, CodeGat commented
Hi @harshula Alternatively, we always give an explicit version on installation I.e. `access-om2@2023.11.22`. 

I'm against the idea of defaults personally. Either the default changes or it remains static. 

If the default is dynamic, users may install the default version every time not knowing it might possibly change, or what the default version is.

If the default is static...is there such thing as a sensible default that isn't just the latest released version? In that case, every deployment would require an update to the SBD. I don't really know what any other sensible defaults would exist that wouldn't require updates each time there was a release.

2023-11-16 01:35 UTC, harshula commented
https://github.com/ACCESS-NRI/spack_packages/issues/32#issuecomment-1794014603

2023-11-16 01:40 UTC, harshula commented
How about using a string like `latest` or `newest`. We could then use the same string in the SPDs.

2023-11-21 02:36 UTC, harshula approved these changes

2023-11-21 02:57 UTC, merged